### ISSUE TITLE
运行指南中的预览报错

### ISSUE THREAD

**Issue by rushb7355608** [yaolunmao/maotu-docs#21]
![image](https://github.com/user-attachments/assets/5f83de87-62e6-4133-a970-c2843eddaa9e)

TypeError: Cannot set properties of undefined (setting 'val')
    at maotu.es.js:40792:12
    at Array.map (<anonymous>)
    at useExportJsonToDoneJson (maotu.es.js:40787:20)
    at Proxy.setImportJson (maotu.es.js:41222:79)
    at mycompoents.vue?t=1722332362367:10:39
    at runtime-core.esm-bundler.js:1548:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:202:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:209:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1528:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:386:32)

**Comment by yaolunmao** [comment]
单独运行是不行的，图元需要用leftAsideStore.registerConfig注册一下啊

**Comment by rushb7355608** [comment]
已解决
